model: 
  name: resnet18
  kwargs:
    weights: ResNet18_Weights.IMAGENET1K_V1
  last_layer: [512, 7]

model_teacher: 
  name: resnet34
  kwargs:
    weights: ResNet34_Weights.IMAGENET1K_V1
  last_layer: [512, 7]

dataset: 
  name: PACS_dataset
  kwargs: 
    domain_list: ["art_painting", "photo", "sketch", "cartoon"]
augmentations:
transforms:
  - name: ToTensor
    kwargs: {}  
  - name: Normalize
    kwargs:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

optimizer:
  name: SGD
  kwargs:
    lr: 0.003
    momentum: 0.9
scheduler:
  name: CosineAnnealingLR
  kwargs:
    eta_min: 0.00003
    T_max: 500
num_epochs: 500
batch_size: 64
temperature: 5

run_id: baseline_distillation
run_id_teacher: baseline_teacher

wandb_project: dist-gen
wandb_entity: gegelyanec
